### ISSUE TITLE
How To Build A Useless Machine :)

### ISSUE THREAD

**Issue by xmliszt** [OpenSUTD/Discovery-Week-Working-Title-#18]
<h1>Session Title</h1>

<h3>How To Build A Useless Machine :) </h3>

<h1>Abstract</h1>

**Useless Machine** is a type of fun machine that when the user does some action the machine will automatically undo the action. In this session, students will use **Arduino** kit to build their interesting useless machines!

<img src="https://www.geek.com/wp-content/uploads/2014/06/Useless-625x350.jpg" width="400" height="200" />

<h1>Student Organisation organising this session</h1>

IEEE SUTD Student Branch

<h1>Session intent (what to expect) </h1>

* Basic knowledge about Arduino and Arduino C programming (data type, operators, conditional, iterative, include library) 
* Hands-on mini activities to familiarise with the knowledge and build up into the final "useless machine"
* Learn how to write pseudocode and draw flowcharts
* Have fun making their first simple robot in uni!

<h1>Session details</h1>

Expecting 30 students to show up 
Venue preferably to be cohort classroom
One session will be 3 hours.
We would like to have two sessions

<h1>Speakers/Workshop facilitators</h1>

SUTD IEEE Exco members

<h1>Logistical details</h1>

* Standard Arduino Kits (buttons, breadboard, motor, motor driver, jumper wires, LEDs)
* Laser Cut Acrylic
* Laptops (Students will bring their own laptops)
* Contact
ieee@club.sutd.edu.sg
yuxuan_li@mymail.sutd.edu.sg 

<img src="https://user-images.githubusercontent.com/44829092/57540876-4dd00f80-7380-11e9-84dc-34458240121a.png" width="400" height="80" />

**Comment by Fishbiscuit** [comment]
what are the dates for your two sessions? and have you secured a venue? otherwise i'll request to book on your behalf.

**Comment by xmliszt** [comment]
> what are the dates for your two sessions? and have you secured a venue? otherwise i'll request to book on your behalf.

@Fishbiscuit Hi! We can accept any available dates but preferably 27th May (Mon) and 6th June (Thur). The venue can help us book? Thank you so much! :)

**Comment by flamanta** [comment]
Ideally we would want to secure CC13 for the activity, but CC14 would be fine as well. Thank you!

**Comment by Fishbiscuit** [comment]
appreciate the added details. also would like to ask what time do you want to hold the session? consolidating to clear with OSA proper

thanks!!

**Comment by flamanta** [comment]
> appreciate the added details. also would like to ask what time do you want to hold the session? consolidating to clear with OSA proper
> 
> thanks!!

7 pm to 10 pm will be fine! thank you~

**Comment by tlkh** [comment]
https://discover.sutd.dev/events.html#useless-machine

Please verify the details

**Comment by shiinx** [comment]
> 
> 
> https://discover.sutd.dev/events.html#useless-machine
> 
> Please verify the details

Hi,
Apologies, is it alright to change the text? 

> Useless Machine is a type of fun machine that when the user does some action the machine will automatically undo the action.

to

> Useless Machine is a type of machine that when the user does an action, the machine will automatically undo that action, thereby making it useless.

And also

> In this session, students will use Arduino kit to build their interesting useless machines!
> 
> Participants will learn basic knowledge about Arduino and Arduino C programming (data type, operators, conditional, iterative, include library). There will be hands-on mini activities to familiarise with the knowledge and build up into the final "useless machine".
> 
> Have fun making their first simple robot in uni! 

to 

> In this session, students will use an Arduino kit to build their interesting useless machines!
> 
> Participants will learn basic knowledge about Arduino and Arduino C programming (data type, operators, conditional, iterative and 'include' library). 
> 
> There will be multiple hands-on mini activities that will eventually build up into the final "useless` machine".
> 
> Sign up now and have fun making your very first Tech in SUTD! 

And if its alright, is it okay to add an additional line at the end? Regarding logistics.

> Remember to bring your laptop and yourself!

**Comment by tlkh** [comment]
Ok I have made the changes!
