### ISSUE TITLE
Ballroom Dancing Intro Session 2

### ISSUE THREAD

**Issue by natng99** [OpenSUTD/Discovery-Week-Working-Title-#19]
**Session Name**

Rock n Roll

**Abstract**

To introduce the freshies to another form of pair dance, one that is apart from the competition dances that we do in standard ballroom.

**Student Organisation organising this session**

SUTD Ballroom Dance

**Session intent (what to expect)**

- Learn how to _rock and roll_, a chill and relaxed dance form
- No prerequisites 

**Session details**

We can cater for approximately 10 participants. The session will be 2 hours long at preferably the dances studio (DS 3-5). We will most likely need to hold it on wednesday or friday when the alumni can come down to assist us in the teaching.

**Speakers/Workshop facilitators**

Alumni and current students will be asked to lead the session . If given the budget, we will also invite our coach to conduct a formal and more depth lesson.

**Logistical details**

Our coach charges $150 per hour, hence we would need $300 if we were to call our coach down.

**Comment by tlkh** [comment]
Ballroom will only have their first session as per discussion in #14 . Closing this.
