### ISSUE TITLE
PIAK PIAK PIAAAAKKK!!!!!

### ISSUE THREAD

**Issue by ziminnn** [OpenSUTD/Discovery-Week-Working-Title-#2]
**Session Name**

A title that captures the intent of the session and is attention-grabbing.

**Abstract**

A short description of the highlights of your session in one or two sentences.

**Student Organisation organising this session**

**Session intent (what to expect)**

- Share with us what you hope your participants will take away from this session (Participants will learn ...)
- Share with us if there are any prerequisites to make the most of this session (Participants will require knowledge of ...)
- *italicise* the specific skills/ takeaways that are quantifiable to help us create a concept map of the sessions we are offering for our incoming Freshmores

**Session details**

Let us know the number of participants you can handle and where you intend to hold it. (if you need a venue, do let us know what sort of venue would be ideal to book). If you have any constraints on the timing or any other matters, do specify as well

**Speakers/Workshop facilitators**

Share with us the background of your facilitators to provide some context for your participants.

**Logistical details**

Help us with the overall resourcing our events. This will give us cue as to how to budget for the event and if there are further constraints we must consider.
Please provide us with your e-mail address so we can notify you once your event has been scheduled.

**Comment by tlkh** [comment]
I'm going to assume this is made by mistake, and #3 is the correct submission.
